-- Create site_settings table for dynamic homepage stats
CREATE TABLE IF NOT EXISTS public.site_settings (
  id bigint generated by default as identity primary key,
  active_mentors text default '500+',
  top_colleges text default '50+',
  average_rating text default '4.8/5',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Policies
-- Everyone can read
DO $$ BEGIN
  CREATE POLICY "Allow public read access on site_settings" ON public.site_settings FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Only admins can update
DO $$ BEGIN
  CREATE POLICY "Allow admin update on site_settings" ON public.site_settings FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Insert default row if not exists
INSERT INTO public.site_settings (id, active_mentors, top_colleges, average_rating)
SELECT 1, '500+', '50+', '4.8/5'
WHERE NOT EXISTS (SELECT 1 FROM public.site_settings);
