-- Create bookings table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_id UUID REFERENCES public.mentors(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    session_time TIMESTAMPTZ NOT NULL,
    duration_minutes INTEGER DEFAULT 60,
    status TEXT DEFAULT 'pending',
    amount_paid INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Students can view own bookings" ON public.bookings;
DROP POLICY IF EXISTS "Mentors can view own bookings" ON public.bookings;
DROP POLICY IF EXISTS "Admins can view all bookings" ON public.bookings;
DROP POLICY IF EXISTS "Users can create bookings" ON public.bookings;
DROP POLICY IF EXISTS "Admins can update bookings" ON public.bookings;

-- Policy: Students can view their own bookings
CREATE POLICY "Students can view own bookings" ON public.bookings
    FOR SELECT
    USING (auth.uid() = student_id);

-- Policy: Mentors can view bookings where they are the mentor
CREATE POLICY "Mentors can view own bookings" ON public.bookings
    FOR SELECT
    USING (auth.uid() = mentor_id);

-- Policy: Admins can view all bookings
CREATE POLICY "Admins can view all bookings" ON public.bookings
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.user_roles
            WHERE user_id = auth.uid()
            AND role = 'admin'
        )
    );

-- Policy: Authenticated users can create bookings
CREATE POLICY "Users can create bookings" ON public.bookings
    FOR INSERT
    WITH CHECK (auth.uid() = student_id);

-- Policy: Admins can update bookings
CREATE POLICY "Admins can update bookings" ON public.bookings
    FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.user_roles
            WHERE user_id = auth.uid()
            AND role = 'admin'
        )
    );
