-- Run this to create ALL missing tables
-- This is safe to run even if some tables exist (it uses IF NOT EXISTS)

-- 1. Create Colleges Table
CREATE TABLE IF NOT EXISTS public.colleges (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  category text not null,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Mentors Table
CREATE TABLE IF NOT EXISTS public.mentors (
  id uuid references auth.users not null primary key,
  college_id bigint references public.colleges(id),
  branch text,
  year text,
  rating numeric default 5.0,
  sessions_count integer default 0,
  price_per_session integer default 0,
  expertise text[],
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Mentor Applications Table
CREATE TABLE IF NOT EXISTS public.mentor_applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  full_name text not null,
  email text not null,
  phone text,
  bio text,
  college_name text, 
  status public.application_status default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create Bookings Table
CREATE TABLE IF NOT EXISTS public.bookings (
  id bigint generated by default as identity primary key,
  mentor_id uuid references public.mentors(id) not null,
  student_id uuid references auth.users not null,
  session_time timestamp with time zone not null,
  duration_minutes integer default 60,
  status text default 'scheduled',
  amount_paid integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable RLS
ALTER TABLE public.colleges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mentors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mentor_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- 6. Policies (Safe to run multiple times, will just error if exists which is fine)

-- Colleges
DO $$ BEGIN
  CREATE POLICY "Allow public read access on colleges" ON public.colleges FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Allow admin full access on colleges" ON public.colleges FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Mentors
DO $$ BEGIN
  CREATE POLICY "Allow public read access on verified mentors" ON public.mentors FOR SELECT USING (is_verified = true);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Allow admin full access on mentors" ON public.mentors FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Mentors can update their own profile" ON public.mentors FOR UPDATE USING (auth.uid() = id);
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Applications
DO $$ BEGIN
  CREATE POLICY "Users can create applications" ON public.mentor_applications FOR INSERT WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Users can view their own applications" ON public.mentor_applications FOR SELECT USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Admins can view all applications" ON public.mentor_applications FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Admins can update applications" ON public.mentor_applications FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Bookings
DO $$ BEGIN
  CREATE POLICY "Users can view their own bookings" ON public.bookings FOR SELECT USING (auth.uid() = student_id OR auth.uid() = mentor_id);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Admins can view all bookings" ON public.bookings FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 7. Insert Dummy Data (Only if empty)
INSERT INTO public.colleges (name, location, category, description)
SELECT 'Indian Institute of Technology, Delhi', 'New Delhi, India', 'Engineering', 'Premier engineering institution known for technical excellence'
WHERE NOT EXISTS (SELECT 1 FROM public.colleges);

INSERT INTO public.colleges (name, location, category, description)
SELECT 'St. Stephen''s College', 'Delhi, India', 'Liberal Arts', 'Prestigious college offering humanities and science programs'
WHERE NOT EXISTS (SELECT 1 FROM public.colleges WHERE name = 'St. Stephen''s College');
