-- Create custom types
create type app_role as enum ('admin', 'mentor', 'student');
create type application_status as enum ('pending', 'approved', 'rejected');

-- Create colleges table
create table public.colleges (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  category text not null,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create mentors table (extends profiles)
create table public.mentors (
  id uuid references auth.users not null primary key,
  college_id bigint references public.colleges(id),
  branch text,
  year text,
  rating numeric default 5.0,
  sessions_count integer default 0,
  price_per_session integer default 0,
  expertise text[],
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create mentor_applications table
create table public.mentor_applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  full_name text not null,
  email text not null,
  phone text,
  bio text,
  college_name text, -- Temporary storage until linked to actual college
  status application_status default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create bookings table
create table public.bookings (
  id bigint generated by default as identity primary key,
  mentor_id uuid references public.mentors(id) not null,
  student_id uuid references auth.users not null,
  session_time timestamp with time zone not null,
  duration_minutes integer default 60,
  status text default 'scheduled', -- scheduled, completed, cancelled
  amount_paid integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.colleges enable row level security;
alter table public.mentors enable row level security;
alter table public.mentor_applications enable row level security;
alter table public.bookings enable row level security;

-- Policies

-- Colleges: Everyone can read, only admins can insert/update/delete
create policy "Allow public read access on colleges"
  on public.colleges for select using (true);

create policy "Allow admin full access on colleges"
  on public.colleges for all
  using (
    exists (
      select 1 from public.user_roles
      where user_id = auth.uid() and role = 'admin'
    )
  );

-- Mentors: Everyone can read verified mentors
create policy "Allow public read access on verified mentors"
  on public.mentors for select
  using (is_verified = true);

create policy "Allow admin full access on mentors"
  on public.mentors for all
  using (
    exists (
      select 1 from public.user_roles
      where user_id = auth.uid() and role = 'admin'
    )
  );
  
create policy "Mentors can update their own profile"
  on public.mentors for update
  using (auth.uid() = id);

-- Mentor Applications: Users can create, Admins can view/update
create policy "Users can create applications"
  on public.mentor_applications for insert
  with check (auth.uid() = user_id);

create policy "Users can view their own applications"
  on public.mentor_applications for select
  using (auth.uid() = user_id);

create policy "Admins can view all applications"
  on public.mentor_applications for select
  using (
    exists (
      select 1 from public.user_roles
      where user_id = auth.uid() and role = 'admin'
    )
  );

create policy "Admins can update applications"
  on public.mentor_applications for update
  using (
    exists (
      select 1 from public.user_roles
      where user_id = auth.uid() and role = 'admin'
    )
  );

-- Bookings: Users see their own, Admins see all
create policy "Users can view their own bookings"
  on public.bookings for select
  using (auth.uid() = student_id or auth.uid() = mentor_id);

create policy "Admins can view all bookings"
  on public.bookings for select
  using (
    exists (
      select 1 from public.user_roles
      where user_id = auth.uid() and role = 'admin'
    )
  );

-- Insert some dummy data for Colleges (since we are migrating)
insert into public.colleges (name, location, category, description) values
('Indian Institute of Technology, Delhi', 'New Delhi, India', 'Engineering', 'Premier engineering institution known for technical excellence'),
('St. Stephen''s College', 'Delhi, India', 'Liberal Arts', 'Prestigious college offering humanities and science programs'),
('Lady Shri Ram College', 'Delhi, India', 'Women''s College', 'Leading women''s college with diverse academic programs'),
('BITS Pilani', 'Pilani, Rajasthan', 'Engineering', 'Top-tier technical and science institution'),
('Miranda House', 'Delhi, India', 'Women''s College', 'Renowned for academic excellence in arts and sciences'),
('Hindu College', 'Delhi, India', 'Liberal Arts', 'Historic college offering diverse undergraduate programs');
